title: Christoph Sager
email: christoph.sager@gmail.com
description: >-
  Developer. Reader. Writer.
twitter_username: ch-sa
github_username:  ch-sa

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# CUSTOM SETTINGS

base_url: /ch-sa

github:
  is_project_page: false

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
