title: Christoph Sager
email: christoph.sager[at]gmail.com
description:
github_username:  ch-sa

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-sitemap

# CUSTOM SETTINGS

base_url: /

github:
  is_project_page: false

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
